name: apsbss-package
channels:
  - apsu
  - conda-forge
  - aps-anl-tag
  - defaults
dependencies:
  - python >=3.9
  - aps-dm-api
  - bluesky
  - ophyd
  - pip
  - pyRestTable
  - pyyaml
  - spec2nexus
  # - pip:
  #   - prompt-toolkit==1.0.15
