name: Publish Sphinx Docs to GitHub Pages
on: [push]

# see: https://sphinx-notes.github.io/pages/
# see: https://github.com/marketplace/actions/sphinx-to-github-pages

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
    # - uses: actions/checkout@v2
      uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Diagnostic
      run: |
        pwd
        ls -lAFgh
        ls -lAFgh ..

    - name: Build and Commit
      uses: sphinx-notes/pages@master
      with:
        documentation_path: docs

    - name: Diagnostic
      run: |
        pwd
        ls -lAFgh
        ls -lAFgh docs

    # - name: Push changes
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     branch: gh-pages